In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import json
import pandas as pd
import os

In [3]:
BASE_PATH = "/content/drive/MyDrive/Class  Materials/Spring 26/490 D/WyScout"
# Change the name of the path as per your need

In [4]:
with open(f"{BASE_PATH}/competitions.json", encoding="utf-8") as f:
    competitions = json.load(f)

competitions_df = pd.DataFrame(competitions)
competitions_df

,name,wyId,format,area,type
0,Italian first division,524,Domestic league,"{'name': 'Italy', 'id': '380', 'alpha3code': '...",club
1,English first division,364,Domestic league,"{'name': 'England', 'id': '0', 'alpha3code': '...",club
2,Spanish first division,795,Domestic league,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",club
3,French first division,412,Domestic league,"{'name': 'France', 'id': '250', 'alpha3code': ...",club
4,German first division,426,Domestic league,"{'name': 'Germany', 'id': '276', 'alpha3code':...",club
5,European Championship,102,International cup,"{'name': '', 'id': 0, 'alpha3code': 'XEU', 'al...",international
6,World Cup,28,International cup,"{'name': '', 'id': 0, 'alpha3code': 'XWO', 'al...",international

In [5]:
os.listdir(f"{BASE_PATH}/matches")

['matches_Italy.json',
 'matches_European_Championship.json',
 'matches_Germany.json',
 'matches_Spain.json',
 'matches_France.json',
 'matches_World_Cup.json',
 'matches_England.json']

In [6]:
with open(f"{BASE_PATH}/matches/matches_England.json", encoding="utf-8") as f:
    matches = json.load(f)

matches_df = pd.DataFrame(matches)
matches_df.head()

,status,roundId,gameweek,teamsData,seasonId,dateutc,winner,venue,wyId,label,date,referees,duration,competitionId
0,Played,4405654,38,"{'1646': {'scoreET': 0, 'coachId': 8880, 'side...",181150,2018-05-13 14:00:00,1659,Turf Moor,2500089,"Burnley - AFC Bournemouth, 1 - 2","May 13, 2018 at 4:00:00 PM GMT+2","[{'refereeId': 385705, 'role': 'referee'}, {'r...",Regular,364
1,Played,4405654,38,"{'1628': {'scoreET': 0, 'coachId': 8357, 'side...",181150,2018-05-13 14:00:00,1628,Selhurst Park,2500090,"Crystal Palace - West Bromwich Albion, 2 - 0","May 13, 2018 at 4:00:00 PM GMT+2","[{'refereeId': 381851, 'role': 'referee'}, {'r...",Regular,364
2,Played,4405654,38,"{'1609': {'scoreET': 0, 'coachId': 7845, 'side...",181150,2018-05-13 14:00:00,1609,The John Smith's Stadium,2500091,"Huddersfield Town - Arsenal, 0 - 1","May 13, 2018 at 4:00:00 PM GMT+2","[{'refereeId': 384965, 'role': 'referee'}, {'r...",Regular,364
3,Played,4405654,38,"{'1651': {'scoreET': 0, 'coachId': 8093, 'side...",181150,2018-05-13 14:00:00,1612,Anfield,2500092,"Liverpool - Brighton & Hove Albion, 4 - 0","May 13, 2018 at 4:00:00 PM GMT+2","[{'refereeId': 385704, 'role': 'referee'}, {'r...",Regular,364
4,Played,4405654,38,"{'1644': {'scoreET': 0, 'coachId': 93112, 'sid...",181150,2018-05-13 14:00:00,1611,Old Trafford,2500093,"Manchester United - Watford, 1 - 0","May 13, 2018 at 4:00:00 PM GMT+2","[{'refereeId': 381853, 'role': 'referee'}, {'r...",Regular,364

In [7]:
with open(f"{BASE_PATH}/players.json") as f:
    players = json.load(f)

players_df = pd.DataFrame(players)
players_df.head()

,passportArea,weight,firstName,middleName,lastName,currentTeamId,birthDate,height,role,birthArea,wyId,foot,shortName,currentNationalTeamId
0,"{'name': 'Turkey', 'id': '792', 'alpha3code': ...",78,Harun,,Tekin,4502,1989-06-17,187,"{'code2': 'GK', 'code3': 'GKP', 'name': 'Goalk...","{'name': 'Turkey', 'id': '792', 'alpha3code': ...",32777,right,H. Tekin,4687
1,"{'name': 'Senegal', 'id': '686', 'alpha3code':...",73,Malang,,Sarr,3775,1999-01-23,182,"{'code2': 'DF', 'code3': 'DEF', 'name': 'Defen...","{'name': 'France', 'id': '250', 'alpha3code': ...",393228,left,M. Sarr,4423
2,"{'name': 'France', 'id': '250', 'alpha3code': ...",72,Over,,Mandanda,3772,1998-10-26,176,"{'code2': 'GK', 'code3': 'GKP', 'name': 'Goalk...","{'name': 'France', 'id': '250', 'alpha3code': ...",393230,,O. Mandanda,null
3,"{'name': 'Senegal', 'id': '686', 'alpha3code':...",82,Alfred John Momar,,N'Diaye,683,1990-03-06,187,"{'code2': 'MD', 'code3': 'MID', 'name': 'Midfi...","{'name': 'France', 'id': '250', 'alpha3code': ...",32793,right,A. N'Diaye,19314
4,"{'name': 'France', 'id': '250', 'alpha3code': ...",84,Ibrahima,,Konat\u00e9,2975,1999-05-25,192,"{'code2': 'DF', 'code3': 'DEF', 'name': 'Defen...","{'name': 'France', 'id': '250', 'alpha3code': ...",393247,right,I. Konat\u00e9,null

In [8]:
players_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3603 entries, 0 to 3602
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   passportArea           3603 non-null   object
 1   weight                 3603 non-null   int64
 2   firstName              3603 non-null   object
 3   middleName             3603 non-null   object
 4   lastName               3603 non-null   object
 5   currentTeamId          3512 non-null   object
 6   birthDate              3603 non-null   object
 7   height                 3603 non-null   int64
 8   role                   3603 non-null   object
 9   birthArea              3603 non-null   object
 10  wyId                   3603 non-null   int64
 11  foot                   3603 non-null   object
 12  shortName              3603 non-null   object
 13  currentNationalTeamId  3603 non-null   object
dtypes: int64(3), object(11)
memory usage: 394.2+ KB

In [9]:
with open(f"{BASE_PATH}/teams.json", encoding="utf-8") as f:
    teams = json.load(f)

teams_df = pd.DataFrame(teams)
teams_df.head()

,city,name,wyId,officialName,area,type
0,Newcastle upon Tyne,Newcastle United,1613,Newcastle United FC,"{'name': 'England', 'id': '0', 'alpha3code': '...",club
1,Vigo,Celta de Vigo,692,Real Club Celta de Vigo,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",club
2,Barcelona,Espanyol,691,Reial Club Deportiu Espanyol,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",club
3,Vitoria-Gasteiz,Deportivo Alav\u00e9s,696,Deportivo Alav\u00e9s,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",club
4,Valencia,Levante,695,Levante UD,"{'name': 'Spain', 'id': '724', 'alpha3code': '...",club

In [10]:
os.listdir(f"{BASE_PATH}/events")

['events_European_Championship.json',
 'events_Italy.json',
 'events_Germany.json',
 'events_England.json',
 'events_World_Cup.json',
 'events_Spain.json',
 'events_France.json']

In [11]:
with open(f"{BASE_PATH}/events/events_England.json", encoding="utf-8") as f:
    events = json.load(f)

events_df = pd.DataFrame(events)
events_df.head()

,eventId,subEventName,tags,playerId,positions,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id
0,8,Simple pass,[{'id': 1801}],25413,"[{'y': 49, 'x': 49}, {'y': 78, 'x': 31}]",2499719,Pass,1609,1H,2.758649,85,177959171
1,8,High pass,[{'id': 1801}],370224,"[{'y': 78, 'x': 31}, {'y': 75, 'x': 51}]",2499719,Pass,1609,1H,4.946850,83,177959172
2,8,Head pass,[{'id': 1801}],3319,"[{'y': 75, 'x': 51}, {'y': 71, 'x': 35}]",2499719,Pass,1609,1H,6.542188,82,177959173
3,8,Head pass,[{'id': 1801}],120339,"[{'y': 71, 'x': 35}, {'y': 95, 'x': 41}]",2499719,Pass,1609,1H,8.143395,82,177959174
4,8,Simple pass,[{'id': 1801}],167145,"[{'y': 95, 'x': 41}, {'y': 88, 'x': 72}]",2499719,Pass,1609,1H,10.302366,85,177959175

In [12]:
events_df["eventName"].value_counts().head(10)

eventName
Pass                       328657
Duel                       176688
Others on the ball          51085
Free Kick                   36423
Interruption                27535
Shot                         8451
Foul                         8138
Save attempt                 3349
Offside                      1558
Goalkeeper leaving line      1266
Name: count, dtype: int64

In [13]:
event_map = pd.read_csv(f"{BASE_PATH}/eventid2name.csv")
event_map.head()

   event  subevent event_label          subevent_label
0      1        10        Duel                Air duel
1      1        11        Duel   Ground attacking duel
2      1        12        Duel   Ground defending duel
3      1        13        Duel  Ground loose ball duel
4      2        20        Foul                    Foul

In [14]:
tag_map = pd.read_csv(f"{BASE_PATH}/tags2name.csv")
tag_map.head()

    Tag           Label     Description
0   101            Goal            Goal
1   102        own_goal        Own goal
2   301          assist          Assist
3   302         keyPass        Key pass
4  1901  counter_attack  Counter attack

# Sign Test

In [15]:
train = []

for file in os.listdir(f"{BASE_PATH}/events"):
    if file.endswith(".json"):
        with open(f"{BASE_PATH}/events/{file}", encoding="utf-8") as f:
            data = json.load(f)
        train.append(pd.DataFrame(data))

train = pd.concat(train, ignore_index=True)
train.head()

,eventId,subEventName,tags,playerId,positions,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id
0,8,Simple pass,[{'id': 1801}],26010,"[{'y': 48, 'x': 50}, {'y': 50, 'x': 47}]",1694390,Pass,4418,1H,1.255990,85,88178642
1,8,Simple pass,[{'id': 1801}],3682,"[{'y': 50, 'x': 47}, {'y': 48, 'x': 41}]",1694390,Pass,4418,1H,2.351908,85,88178643
2,8,Simple pass,[{'id': 1801}],31528,"[{'y': 48, 'x': 41}, {'y': 35, 'x': 32}]",1694390,Pass,4418,1H,3.241028,85,88178644
3,8,High pass,[{'id': 1802}],7855,"[{'y': 35, 'x': 32}, {'y': 6, 'x': 89}]",1694390,Pass,4418,1H,6.033681,83,88178645
4,1,Ground defending duel,"[{'id': 702}, {'id': 1801}]",25437,"[{'y': 6, 'x': 89}, {'y': 0, 'x': 85}]",1694390,Duel,4418,1H,13.143591,12,88178646

In [16]:
with open(f"{BASE_PATH}/players.json", encoding="utf-8") as f:
    players = json.load(f)

player_df = pd.DataFrame(players)
player_df.head()

,passportArea,weight,firstName,middleName,lastName,currentTeamId,birthDate,height,role,birthArea,wyId,foot,shortName,currentNationalTeamId
0,"{'name': 'Turkey', 'id': '792', 'alpha3code': ...",78,Harun,,Tekin,4502,1989-06-17,187,"{'code2': 'GK', 'code3': 'GKP', 'name': 'Goalk...","{'name': 'Turkey', 'id': '792', 'alpha3code': ...",32777,right,H. Tekin,4687
1,"{'name': 'Senegal', 'id': '686', 'alpha3code':...",73,Malang,,Sarr,3775,1999-01-23,182,"{'code2': 'DF', 'code3': 'DEF', 'name': 'Defen...","{'name': 'France', 'id': '250', 'alpha3code': ...",393228,left,M. Sarr,4423
2,"{'name': 'France', 'id': '250', 'alpha3code': ...",72,Over,,Mandanda,3772,1998-10-26,176,"{'code2': 'GK', 'code3': 'GKP', 'name': 'Goalk...","{'name': 'France', 'id': '250', 'alpha3code': ...",393230,,O. Mandanda,null
3,"{'name': 'Senegal', 'id': '686', 'alpha3code':...",82,Alfred John Momar,,N'Diaye,683,1990-03-06,187,"{'code2': 'MD', 'code3': 'MID', 'name': 'Midfi...","{'name': 'France', 'id': '250', 'alpha3code': ...",32793,right,A. N'Diaye,19314
4,"{'name': 'France', 'id': '250', 'alpha3code': ...",84,Ibrahima,,Konat\u00e9,2975,1999-05-25,192,"{'code2': 'DF', 'code3': 'DEF', 'name': 'Defen...","{'name': 'France', 'id': '250', 'alpha3code': ...",393247,right,I. Konat\u00e9,null

In [17]:
# take shots only
shots = train.loc[train["subEventName"] == "Shot"]

In [18]:
son_id = player_df.loc[
    player_df["shortName"] == "Son Heung-Min",
    "wyId"
].iloc[0]
# get son's shots
son_shots = shots.loc[shots["playerId"] == son_id]
len(son_shots)

82

In [19]:
# left leg shots
lefty_shots = son_shots.loc[
    son_shots.apply(lambda x: {'id': 401} in x.tags, axis=1)
]

# right leg shots
righty_shots = son_shots.loc[
    son_shots.apply(lambda x: {'id': 402} in x.tags, axis=1)
]

len(lefty_shots), len(righty_shots)

(32, 47)

In [20]:
# create list with +1 for left foot shots and -1 for right foot shots
l = [1] * len(lefty_shots)
l.extend([-1] * len(righty_shots))

In [21]:
from statsmodels.stats.descriptivestats import sign_test

test_stat, p_value = sign_test(l, mu0=0)
test_stat, p_value

(np.float64(-7.5), np.float64(0.11466035574580133))

# T Test

In [ ]:
# 1️⃣ Mount Drive and define base path
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd, numpy as np, json, os, pathlib, warnings
warnings.filterwarnings('ignore')

BASE_PATH = "/content/drive/MyDrive/490 D/WyScout"

# 2️⃣ Load all team metadata
with open(f"{BASE_PATH}/teams.json", encoding="utf-8") as f:
    teams = json.load(f)
teams_df = pd.DataFrame(teams).rename(columns={"wyId": "teamId"})

# 3️⃣ Load events
events_df = []
for file in os.listdir(f"{BASE_PATH}/events"):
    if file.endswith(".json"):
        with open(f"{BASE_PATH}/events/{file}", encoding="utf-8") as f:
            data = json.load(f)
        events_df.append(pd.DataFrame(data))
events_df = pd.concat(events_df, ignore_index=True)

# 4️⃣ Filter Corners
corners = events_df[events_df["subEventName"] == "Corner"]

# 5️⃣ Count corners per team per match
corners_by_game = (
    corners.groupby(["teamId", "matchId"])
    .size()
    .reset_index(name="counts")
)

# 6️⃣ Merge team names
corners_by_game = corners_by_game.merge(
    teams_df[["teamId", "name"]], on="teamId", how="left"
)

# 7️⃣ One-sample t-test: Manchester City vs 6 corners
city_corners = corners_by_game.loc[
    corners_by_game["name"] == "Manchester City", "counts"
]

from scipy.stats import ttest_1samp

t_stat, p_val = ttest_1samp(city_corners, popmean=6)
print(f"One-sample t-test (City vs 6): t={t_stat:.2f}, p={p_val:.3f}")
if p_val < 0.05:
    print("Reject H0: City takes more than 6 corners per match.")
else:
    print("Cannot reject H0.")

# 8️⃣ Two-sample t-test: Liverpool vs Everton
liverpool = corners_by_game.loc[
    corners_by_game["name"] == "Liverpool", "counts"
]
everton = corners_by_game.loc[
    corners_by_game["name"] == "Everton", "counts"
]

from scipy.stats import ttest_ind

t_stat2, p_val2 = ttest_ind(liverpool, everton, equal_var=True)
print(f"Two-sample t-test: t={t_stat2:.2f}, p={p_val2:.3f}")
if p_val2 < 0.05:
    print("Reject H0: Corners differ.")
else:
    print("Cannot reject H0: No strong difference in corners.")

In [26]:
with open(f"{BASE_PATH}/teams.json", encoding="utf-8") as f:
    teams = json.load(f)
teams_df = pd.DataFrame(teams).rename(columns={"wyId": "teamId"})

events_df = []
for file in os.listdir(f"{BASE_PATH}/events"):
    if file.endswith(".json"):
        with open(f"{BASE_PATH}/events/{file}", encoding="utf-8") as f:
            data = json.load(f)
        events_df.append(pd.DataFrame(data))
events_df = pd.concat(events_df, ignore_index=True)

# Filter Corners
corners = events_df[events_df["subEventName"] == "Corner"]

# Count corners per team per match
corners_by_game = (
    corners.groupby(["teamId", "matchId"])
    .size()
    .reset_index(name="counts")
)

# Merge team names
corners_by_game = corners_by_game.merge(
    teams_df[["teamId", "name"]], on="teamId", how="left"
)

# One-sample t-test: Manchester City vs 6 corners
city_corners = corners_by_game.loc[
    corners_by_game["name"] == "Manchester City", "counts"
]

from scipy.stats import ttest_1samp

t_stat, p_val = ttest_1samp(city_corners, popmean=6)
print(f"One-sample t-test (City vs 6): t={t_stat:.2f}, p={p_val:.3f}")
if p_val < 0.05:
    print("Reject H0: City takes more than 6 corners per match.")
else:
    print("Cannot reject H0.")

One-sample t-test (City vs 6): t=2.82, p=0.008
Reject H0: City takes more than 6 corners per match.

In [27]:

# 8️⃣ Two-sample t-test: Liverpool vs Everton
liverpool = corners_by_game.loc[
    corners_by_game["name"] == "Liverpool", "counts"
]
everton = corners_by_game.loc[
    corners_by_game["name"] == "Everton", "counts"
]

from scipy.stats import ttest_ind

t_stat2, p_val2 = ttest_ind(liverpool, everton, equal_var=True)
print(f"Two-sample t-test: t={t_stat2:.2f}, p={p_val2:.3f}")
if p_val2 < 0.05:
    print("Reject H0: Corners differ.")
else:
    print("Cannot reject H0: No strong difference in corners.")

Two-sample t-test: t=2.86, p=0.005
Reject H0: Corners differ.